/* Auto-generated by train.py — do not edit manually.
 * Model: RandomForest(n_estimators=10, max_depth=10)
 * Samples: 1574, Features: 9
 * CV accuracy: 0.991
 *
 * Input: double[9] — feature vector (see FEATURE_NAMES)
 * Output: double[2] — [P(FORCE_DOWN), P(FORCE_UP)]
 */

#include <math.h>
#define inf INFINITY

static const double _leaf_down[2] = {1.0, 0.0};
static const double _leaf_up[2]   = {0.0, 1.0};

#include <string.h>
void add_vectors(double *v1, double *v2, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] + v2[i];
}
void mul_vector_number(double *v1, double num, int size, double *result) {
    for(int i = 0; i < size; ++i)
        result[i] = v1[i] * num;
}
void score(double * input, double * output) {
    double var0[2];
    double var1[2];
    double var2[2];
    double var3[2];
    double var4[2];
    double var5[2];
    double var6[2];
    double var7[2];
    double var8[2];
    double var9[2];
    double var10[2];
    if (input[3] <= -0.26483154296875) {
        if (input[5] <= -89.46052551269531) {
            memcpy(var10, _leaf_down, 2 * sizeof(double));
        } else {
            memcpy(var10, _leaf_up, 2 * sizeof(double));
        }
    } else {
        if (input[1] <= 5.119999885559082) {
            memcpy(var10, _leaf_down, 2 * sizeof(double));
        } else {
            if (input[4] <= 4942.35009765625) {
                if (input[5] <= 238.59172821044922) {
                    if (input[1] <= 9.639999866485596) {
                        if (input[6] <= -0.23436090350151062) {
                            if (input[7] <= -0.20880126953125) {
                                memcpy(var10, _leaf_up, 2 * sizeof(double));
                            } else {
                                if (input[7] <= -0.20635986328125) {
                                    if (input[5] <= 83.17744445800781) {
                                        memcpy(var10, _leaf_up, 2 * sizeof(double));
                                    } else {
                                        if (input[2] <= 8.15500020980835) {
                                            memcpy(var10, _leaf_up, 2 * sizeof(double));
                                        } else {
                                            memcpy(var10, _leaf_down, 2 * sizeof(double));
                                        }
                                    }
                                } else {
                                    memcpy(var10, _leaf_down, 2 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[3] <= 0.0523681640625) {
                                memcpy(var10, _leaf_down, 2 * sizeof(double));
                            } else {
                                if (input[0] <= 7381.0) {
                                    memcpy(var10, _leaf_down, 2 * sizeof(double));
                                } else {
                                    memcpy(var10, _leaf_up, 2 * sizeof(double));
                                }
                            }
                        }
                    } else {
                        if (input[6] <= -1.8517293334007263) {
                            memcpy(var10, _leaf_up, 2 * sizeof(double));
                        } else {
                            if (input[2] <= 7.105000019073486) {
                                if (input[5] <= 40.014286041259766) {
                                    memcpy(var10, _leaf_down, 2 * sizeof(double));
                                } else {
                                    memcpy(var10, _leaf_up, 2 * sizeof(double));
                                }
                            } else {
                                memcpy(var10, _leaf_up, 2 * sizeof(double));
                            }
                        }
                    }
                } else {
                    if (input[8] <= 19.98653793334961) {
                        memcpy(var10, _leaf_down, 2 * sizeof(double));
                    } else {
                        memcpy(var10, _leaf_up, 2 * sizeof(double));
                    }
                }
            } else {
                if (input[8] <= 46.6501579284668) {
                    if (input[5] <= 69.69060325622559) {
                        memcpy(var10, _leaf_down, 2 * sizeof(double));
                    } else {
                        if (input[4] <= 5864.1748046875) {
                            if (input[6] <= 0.0008796992478892207) {
                                memcpy(var10, _leaf_up, 2 * sizeof(double));
                            } else {
                                memcpy(var10, _leaf_down, 2 * sizeof(double));
                            }
                        } else {
                            memcpy(var10, _leaf_up, 2 * sizeof(double));
                        }
                    }
                } else {
                    memcpy(var10, _leaf_down, 2 * sizeof(double));
                }
            }
        }
    }
    double var11[2];
    if (input[7] <= 0.081298828125) {
        if (input[2] <= 3.319999933242798) {
            if (input[6] <= -1.972545087337494) {
                memcpy(var11, _leaf_up, 2 * sizeof(double));
            } else {
                if (input[8] <= 78.64652633666992) {
                    memcpy(var11, _leaf_down, 2 * sizeof(double));
                } else {
                    if (input[0] <= 8816.0) {
                        memcpy(var11, _leaf_down, 2 * sizeof(double));
                    } else {
                        memcpy(var11, _leaf_up, 2 * sizeof(double));
                    }
                }
            }
        } else {
            if (input[5] <= 230.7176742553711) {
                if (input[1] <= 9.75499963760376) {
                    if (input[0] <= 10749.5) {
                        if (input[5] <= 55.48533821105957) {
                            memcpy(var11, _leaf_down, 2 * sizeof(double));
                        } else {
                            if (input[1] <= 5.9700000286102295) {
                                if (input[8] <= 20.435672760009766) {
                                    memcpy(var11, _leaf_down, 2 * sizeof(double));
                                } else {
                                    memcpy(var11, _leaf_up, 2 * sizeof(double));
                                }
                            } else {
                                if (input[0] <= 3395.5) {
                                    if (input[7] <= -0.19537353515625) {
                                        if (input[3] <= 0.0089111328125) {
                                            memcpy(var11, _leaf_down, 2 * sizeof(double));
                                        } else {
                                            memcpy(var11, _leaf_up, 2 * sizeof(double));
                                        }
                                    } else {
                                        memcpy(var11, _leaf_down, 2 * sizeof(double));
                                    }
                                } else {
                                    if (input[3] <= 0.04095458984375) {
                                        memcpy(var11, _leaf_down, 2 * sizeof(double));
                                    } else {
                                        memcpy(var11, _leaf_up, 2 * sizeof(double));
                                    }
                                }
                            }
                        }
                    } else {
                        memcpy(var11, _leaf_up, 2 * sizeof(double));
                    }
                } else {
                    if (input[0] <= 2238.0) {
                        memcpy(var11, _leaf_down, 2 * sizeof(double));
                    } else {
                        if (input[2] <= 5.375) {
                            memcpy(var11, _leaf_down, 2 * sizeof(double));
                        } else {
                            memcpy(var11, _leaf_up, 2 * sizeof(double));
                        }
                    }
                }
            } else {
                if (input[3] <= -0.065185546875) {
                    if (input[8] <= 23.6003360748291) {
                        memcpy(var11, _leaf_down, 2 * sizeof(double));
                    } else {
                        memcpy(var11, _leaf_up, 2 * sizeof(double));
                    }
                } else {
                    memcpy(var11, _leaf_up, 2 * sizeof(double));
                }
            }
        }
    } else {
        if (input[0] <= 19609.0) {
            memcpy(var11, _leaf_down, 2 * sizeof(double));
        } else {
            memcpy(var11, _leaf_up, 2 * sizeof(double));
        }
    }
    add_vectors(var10, var11, 2, var9);
    double var12[2];
    if (input[7] <= 0.2115478515625) {
        if (input[2] <= 0.1850000061094761) {
            if (input[6] <= -1.8806766867637634) {
                if (input[8] <= 76.00259017944336) {
                    memcpy(var12, _leaf_down, 2 * sizeof(double));
                } else {
                    memcpy(var12, _leaf_up, 2 * sizeof(double));
                }
            } else {
                memcpy(var12, _leaf_down, 2 * sizeof(double));
            }
        } else {
            if (input[5] <= 225.24323272705078) {
                if (input[0] <= 8525.5) {
                    if (input[5] <= 46.4906005859375) {
                        memcpy(var12, _leaf_down, 2 * sizeof(double));
                    } else {
                        if (input[4] <= 2130.0750732421875) {
                            if (input[1] <= 9.519999980926514) {
                                if (input[3] <= 0.01776123046875) {
                                    memcpy(var12, _leaf_down, 2 * sizeof(double));
                                } else {
                                    if (input[0] <= 2830.0) {
                                        memcpy(var12, _leaf_down, 2 * sizeof(double));
                                    } else {
                                        memcpy(var12, _leaf_up, 2 * sizeof(double));
                                    }
                                }
                            } else {
                                memcpy(var12, _leaf_up, 2 * sizeof(double));
                            }
                        } else {
                            memcpy(var12, _leaf_down, 2 * sizeof(double));
                        }
                    }
                } else {
                    memcpy(var12, _leaf_up, 2 * sizeof(double));
                }
            } else {
                if (input[0] <= 14266.0) {
                    if (input[7] <= -0.1131591796875) {
                        memcpy(var12, _leaf_up, 2 * sizeof(double));
                    } else {
                        memcpy(var12, _leaf_down, 2 * sizeof(double));
                    }
                } else {
                    memcpy(var12, _leaf_up, 2 * sizeof(double));
                }
            }
        }
    } else {
        if (input[6] <= 0.02045112858468201) {
            memcpy(var12, _leaf_down, 2 * sizeof(double));
        } else {
            if (input[0] <= 19841.0) {
                memcpy(var12, _leaf_down, 2 * sizeof(double));
            } else {
                if (input[5] <= -89.84360885620117) {
                    memcpy(var12, _leaf_down, 2 * sizeof(double));
                } else {
                    memcpy(var12, _leaf_up, 2 * sizeof(double));
                }
            }
        }
    }
    add_vectors(var9, var12, 2, var8);
    double var13[2];
    if (input[3] <= -0.178955078125) {
        if (input[0] <= 19852.5) {
            memcpy(var13, _leaf_down, 2 * sizeof(double));
        } else {
            if (input[6] <= 0.12102255970239639) {
                if (input[4] <= 22611.275390625) {
                    memcpy(var13, _leaf_up, 2 * sizeof(double));
                } else {
                    memcpy(var13, _leaf_down, 2 * sizeof(double));
                }
            } else {
                memcpy(var13, _leaf_up, 2 * sizeof(double));
            }
        }
    } else {
        if (input[5] <= 86.7744369506836) {
            if (input[5] <= 46.82518768310547) {
                memcpy(var13, _leaf_down, 2 * sizeof(double));
            } else {
                if (input[4] <= 2073.4750366210938) {
                    if (input[2] <= 5.384999990463257) {
                        memcpy(var13, _leaf_down, 2 * sizeof(double));
                    } else {
                        memcpy(var13, _leaf_up, 2 * sizeof(double));
                    }
                } else {
                    memcpy(var13, _leaf_down, 2 * sizeof(double));
                }
            }
        } else {
            if (input[2] <= 0.19000000320374966) {
                memcpy(var13, _leaf_down, 2 * sizeof(double));
            } else {
                if (input[5] <= 225.24323272705078) {
                    if (input[6] <= -1.1413759589195251) {
                        memcpy(var13, _leaf_up, 2 * sizeof(double));
                    } else {
                        if (input[4] <= 2195.675048828125) {
                            if (input[1] <= 7.5950000286102295) {
                                if (input[0] <= 4264.5) {
                                    memcpy(var13, _leaf_down, 2 * sizeof(double));
                                } else {
                                    memcpy(var13, _leaf_up, 2 * sizeof(double));
                                }
                            } else {
                                if (input[2] <= 8.165000438690186) {
                                    memcpy(var13, _leaf_up, 2 * sizeof(double));
                                } else {
                                    memcpy(var13, _leaf_down, 2 * sizeof(double));
                                }
                            }
                        } else {
                            if (input[4] <= 4294.675048828125) {
                                memcpy(var13, _leaf_down, 2 * sizeof(double));
                            } else {
                                memcpy(var13, _leaf_up, 2 * sizeof(double));
                            }
                        }
                    }
                } else {
                    if (input[3] <= -0.06353759765625) {
                        if (input[1] <= 7.284999847412109) {
                            memcpy(var13, _leaf_down, 2 * sizeof(double));
                        } else {
                            memcpy(var13, _leaf_up, 2 * sizeof(double));
                        }
                    } else {
                        memcpy(var13, _leaf_up, 2 * sizeof(double));
                    }
                }
            }
        }
    }
    add_vectors(var8, var13, 2, var7);
    double var14[2];
    if (input[7] <= 0.14776611328125) {
        if (input[5] <= 106.48120498657227) {
            if (input[5] <= 86.7744369506836) {
                if (input[8] <= 54.114871978759766) {
                    if (input[7] <= -0.2574462890625) {
                        if (input[2] <= 0.2900000214576721) {
                            memcpy(var14, _leaf_up, 2 * sizeof(double));
                        } else {
                            memcpy(var14, _leaf_down, 2 * sizeof(double));
                        }
                    } else {
                        if (input[2] <= 7.740000009536743) {
                            memcpy(var14, _leaf_down, 2 * sizeof(double));
                        } else {
                            if (input[6] <= -0.3705977275967598) {
                                memcpy(var14, _leaf_up, 2 * sizeof(double));
                            } else {
                                memcpy(var14, _leaf_down, 2 * sizeof(double));
                            }
                        }
                    }
                } else {
                    if (input[2] <= 4.354999899864197) {
                        memcpy(var14, _leaf_down, 2 * sizeof(double));
                    } else {
                        memcpy(var14, _leaf_up, 2 * sizeof(double));
                    }
                }
            } else {
                if (input[0] <= 3219.5) {
                    if (input[4] <= 1540.2750244140625) {
                        memcpy(var14, _leaf_down, 2 * sizeof(double));
                    } else {
                        memcpy(var14, _leaf_up, 2 * sizeof(double));
                    }
                } else {
                    if (input[6] <= -0.0021766916615888476) {
                        memcpy(var14, _leaf_down, 2 * sizeof(double));
                    } else {
                        if (input[3] <= 0.0426025390625) {
                            memcpy(var14, _leaf_down, 2 * sizeof(double));
                        } else {
                            memcpy(var14, _leaf_up, 2 * sizeof(double));
                        }
                    }
                }
            }
        } else {
            if (input[1] <= 2.719999904744327) {
                memcpy(var14, _leaf_down, 2 * sizeof(double));
            } else {
                if (input[4] <= 4724.97509765625) {
                    if (input[1] <= 9.529999732971191) {
                        if (input[0] <= 5241.0) {
                            if (input[3] <= 0.055419921875) {
                                if (input[2] <= 7.720000267028809) {
                                    memcpy(var14, _leaf_down, 2 * sizeof(double));
                                } else {
                                    if (input[6] <= -0.5130526274442673) {
                                        memcpy(var14, _leaf_down, 2 * sizeof(double));
                                    } else {
                                        if (input[3] <= 0.0303955078125) {
                                            memcpy(var14, _leaf_down, 2 * sizeof(double));
                                        } else {
                                            memcpy(var14, _leaf_up, 2 * sizeof(double));
                                        }
                                    }
                                }
                            } else {
                                memcpy(var14, _leaf_up, 2 * sizeof(double));
                            }
                        } else {
                            if (input[7] <= -0.11810302734375) {
                                if (input[3] <= -0.03204345703125) {
                                    memcpy(var14, _leaf_down, 2 * sizeof(double));
                                } else {
                                    memcpy(var14, _leaf_up, 2 * sizeof(double));
                                }
                            } else {
                                if (input[4] <= 2822.2750244140625) {
                                    memcpy(var14, _leaf_up, 2 * sizeof(double));
                                } else {
                                    memcpy(var14, _leaf_down, 2 * sizeof(double));
                                }
                            }
                        }
                    } else {
                        memcpy(var14, _leaf_up, 2 * sizeof(double));
                    }
                } else {
                    if (input[3] <= -0.065185546875) {
                        if (input[8] <= 19.245725631713867) {
                            memcpy(var14, _leaf_down, 2 * sizeof(double));
                        } else {
                            memcpy(var14, _leaf_up, 2 * sizeof(double));
                        }
                    } else {
                        memcpy(var14, _leaf_up, 2 * sizeof(double));
                    }
                }
            }
        }
    } else {
        if (input[5] <= -89.46052551269531) {
            memcpy(var14, _leaf_down, 2 * sizeof(double));
        } else {
            memcpy(var14, _leaf_up, 2 * sizeof(double));
        }
    }
    add_vectors(var7, var14, 2, var6);
    double var15[2];
    if (input[1] <= 11.605000019073486) {
        if (input[5] <= 160.6669158935547) {
            if (input[2] <= 8.555000305175781) {
                if (input[3] <= -0.2113037109375) {
                    memcpy(var15, _leaf_up, 2 * sizeof(double));
                } else {
                    if (input[5] <= 73.67668914794922) {
                        if (input[2] <= 7.730000019073486) {
                            memcpy(var15, _leaf_down, 2 * sizeof(double));
                        } else {
                            if (input[8] <= 5.034104585647583) {
                                memcpy(var15, _leaf_down, 2 * sizeof(double));
                            } else {
                                memcpy(var15, _leaf_up, 2 * sizeof(double));
                            }
                        }
                    } else {
                        if (input[1] <= 9.429999828338623) {
                            if (input[2] <= 8.300000190734863) {
                                if (input[8] <= 4.859493017196655) {
                                    memcpy(var15, _leaf_down, 2 * sizeof(double));
                                } else {
                                    if (input[4] <= 2159.60009765625) {
                                        if (input[7] <= -0.1566162109375) {
                                            memcpy(var15, (double[]){0.5555555555555556, 0.4444444444444444}, 2 * sizeof(double));
                                        } else {
                                            memcpy(var15, _leaf_down, 2 * sizeof(double));
                                        }
                                    } else {
                                        memcpy(var15, _leaf_down, 2 * sizeof(double));
                                    }
                                }
                            } else {
                                memcpy(var15, _leaf_up, 2 * sizeof(double));
                            }
                        } else {
                            memcpy(var15, _leaf_up, 2 * sizeof(double));
                        }
                    }
                }
            } else {
                memcpy(var15, _leaf_up, 2 * sizeof(double));
            }
        } else {
            if (input[2] <= 0.8149999883025885) {
                memcpy(var15, _leaf_down, 2 * sizeof(double));
            } else {
                if (input[0] <= 5241.0) {
                    memcpy(var15, _leaf_down, 2 * sizeof(double));
                } else {
                    if (input[1] <= 6.224999904632568) {
                        if (input[6] <= -0.04973684262949973) {
                            memcpy(var15, _leaf_up, 2 * sizeof(double));
                        } else {
                            memcpy(var15, _leaf_down, 2 * sizeof(double));
                        }
                    } else {
                        memcpy(var15, _leaf_up, 2 * sizeof(double));
                    }
                }
            }
        }
    } else {
        if (input[5] <= -89.46052551269531) {
            memcpy(var15, _leaf_down, 2 * sizeof(double));
        } else {
            if (input[4] <= 1009.3500061035156) {
                memcpy(var15, _leaf_down, 2 * sizeof(double));
            } else {
                if (input[4] <= 2423.0250244140625) {
                    if (input[2] <= 4.0899999141693115) {
                        memcpy(var15, _leaf_down, 2 * sizeof(double));
                    } else {
                        memcpy(var15, _leaf_up, 2 * sizeof(double));
                    }
                } else {
                    memcpy(var15, _leaf_up, 2 * sizeof(double));
                }
            }
        }
    }
    add_vectors(var6, var15, 2, var5);
    double var16[2];
    if (input[7] <= 0.205322265625) {
        if (input[5] <= 109.66954803466797) {
            if (input[5] <= 47.54812049865723) {
                if (input[7] <= -0.25872802734375) {
                    if (input[7] <= -0.26092529296875) {
                        memcpy(var16, _leaf_down, 2 * sizeof(double));
                    } else {
                        memcpy(var16, _leaf_up, 2 * sizeof(double));
                    }
                } else {
                    memcpy(var16, _leaf_down, 2 * sizeof(double));
                }
            } else {
                if (input[6] <= -0.3607669174671173) {
                    if (input[4] <= 2130.0750732421875) {
                        memcpy(var16, _leaf_up, 2 * sizeof(double));
                    } else {
                        memcpy(var16, _leaf_down, 2 * sizeof(double));
                    }
                } else {
                    if (input[3] <= 0.0516357421875) {
                        memcpy(var16, _leaf_down, 2 * sizeof(double));
                    } else {
                        if (input[8] <= 10.28095281124115) {
                            memcpy(var16, _leaf_up, 2 * sizeof(double));
                        } else {
                            memcpy(var16, _leaf_down, 2 * sizeof(double));
                        }
                    }
                }
            }
        } else {
            if (input[2] <= 0.1350000062957406) {
                if (input[6] <= 0.0638157888315618) {
                    memcpy(var16, _leaf_down, 2 * sizeof(double));
                } else {
                    memcpy(var16, _leaf_up, 2 * sizeof(double));
                }
            } else {
                if (input[5] <= 225.24323272705078) {
                    if (input[1] <= 9.420000076293945) {
                        if (input[3] <= 0.040771484375) {
                            if (input[6] <= 0.05190225411206484) {
                                if (input[5] <= 128.83909606933594) {
                                    if (input[0] <= 3395.5) {
                                        memcpy(var16, _leaf_up, 2 * sizeof(double));
                                    } else {
                                        memcpy(var16, _leaf_down, 2 * sizeof(double));
                                    }
                                } else {
                                    memcpy(var16, _leaf_down, 2 * sizeof(double));
                                }
                            } else {
                                memcpy(var16, _leaf_up, 2 * sizeof(double));
                            }
                        } else {
                            memcpy(var16, _leaf_up, 2 * sizeof(double));
                        }
                    } else {
                        memcpy(var16, _leaf_up, 2 * sizeof(double));
                    }
                } else {
                    if (input[6] <= -0.0004436090821400285) {
                        memcpy(var16, _leaf_up, 2 * sizeof(double));
                    } else {
                        if (input[1] <= 6.699999809265137) {
                            memcpy(var16, _leaf_down, 2 * sizeof(double));
                        } else {
                            memcpy(var16, _leaf_up, 2 * sizeof(double));
                        }
                    }
                }
            }
        }
    } else {
        if (input[0] <= 19852.5) {
            memcpy(var16, _leaf_down, 2 * sizeof(double));
        } else {
            memcpy(var16, _leaf_up, 2 * sizeof(double));
        }
    }
    add_vectors(var5, var16, 2, var4);
    double var17[2];
    if (input[7] <= 0.18780517578125) {
        if (input[8] <= 11.140443801879883) {
            if (input[3] <= 0.0482177734375) {
                if (input[7] <= -0.24749755859375) {
                    memcpy(var17, _leaf_up, 2 * sizeof(double));
                } else {
                    if (input[8] <= 5.664646625518799) {
                        memcpy(var17, _leaf_down, 2 * sizeof(double));
                    } else {
                        if (input[6] <= -0.4086315780878067) {
                            if (input[8] <= 8.20379638671875) {
                                if (input[4] <= 2062.949951171875) {
                                    memcpy(var17, _leaf_up, 2 * sizeof(double));
                                } else {
                                    memcpy(var17, _leaf_down, 2 * sizeof(double));
                                }
                            } else {
                                memcpy(var17, _leaf_down, 2 * sizeof(double));
                            }
                        } else {
                            memcpy(var17, _leaf_down, 2 * sizeof(double));
                        }
                    }
                }
            } else {
                if (input[1] <= 6.015000104904175) {
                    memcpy(var17, _leaf_down, 2 * sizeof(double));
                } else {
                    memcpy(var17, _leaf_up, 2 * sizeof(double));
                }
            }
        } else {
            if (input[5] <= 304.47630310058594) {
                if (input[2] <= 7.380000114440918) {
                    if (input[4] <= 20672.8994140625) {
                        if (input[5] <= 43.021053314208984) {
                            if (input[6] <= -1.8809060454368591) {
                                if (input[0] <= 6539.5) {
                                    memcpy(var17, _leaf_down, 2 * sizeof(double));
                                } else {
                                    memcpy(var17, _leaf_up, 2 * sizeof(double));
                                }
                            } else {
                                memcpy(var17, _leaf_down, 2 * sizeof(double));
                            }
                        } else {
                            if (input[8] <= 31.360146522521973) {
                                if (input[1] <= 9.40999984741211) {
                                    if (input[0] <= 5241.0) {
                                        memcpy(var17, _leaf_down, 2 * sizeof(double));
                                    } else {
                                        if (input[3] <= -0.03582763671875) {
                                            memcpy(var17, _leaf_down, 2 * sizeof(double));
                                        } else {
                                            memcpy(var17, _leaf_up, 2 * sizeof(double));
                                        }
                                    }
                                } else {
                                    memcpy(var17, _leaf_up, 2 * sizeof(double));
                                }
                            } else {
                                memcpy(var17, _leaf_up, 2 * sizeof(double));
                            }
                        }
                    } else {
                        if (input[4] <= 21030.0244140625) {
                            memcpy(var17, _leaf_up, 2 * sizeof(double));
                        } else {
                            memcpy(var17, _leaf_down, 2 * sizeof(double));
                        }
                    }
                } else {
                    if (input[8] <= 12.728052139282227) {
                        memcpy(var17, _leaf_down, 2 * sizeof(double));
                    } else {
                        memcpy(var17, _leaf_up, 2 * sizeof(double));
                    }
                }
            } else {
                if (input[0] <= 5507.0) {
                    memcpy(var17, _leaf_down, 2 * sizeof(double));
                } else {
                    if (input[2] <= inf) {
                        if (input[3] <= -0.06353759765625) {
                            if (input[7] <= 0.022216796875) {
                                memcpy(var17, _leaf_down, 2 * sizeof(double));
                            } else {
                                memcpy(var17, _leaf_up, 2 * sizeof(double));
                            }
                        } else {
                            memcpy(var17, _leaf_up, 2 * sizeof(double));
                        }
                    } else {
                        memcpy(var17, _leaf_down, 2 * sizeof(double));
                    }
                }
            }
        }
    } else {
        if (input[5] <= -93.63533782958984) {
            memcpy(var17, _leaf_down, 2 * sizeof(double));
        } else {
            memcpy(var17, _leaf_up, 2 * sizeof(double));
        }
    }
    add_vectors(var4, var17, 2, var3);
    double var18[2];
    if (input[7] <= 0.081298828125) {
        if (input[5] <= 93.52481079101562) {
            if (input[8] <= 77.84536743164062) {
                if (input[7] <= -0.204833984375) {
                    if (input[4] <= 2037.5499877929688) {
                        if (input[2] <= 7.620000123977661) {
                            if (input[1] <= 10.84000015258789) {
                                memcpy(var18, _leaf_down, 2 * sizeof(double));
                            } else {
                                if (input[3] <= 0.0169677734375) {
                                    memcpy(var18, _leaf_up, 2 * sizeof(double));
                                } else {
                                    memcpy(var18, _leaf_down, 2 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var18, _leaf_up, 2 * sizeof(double));
                        }
                    } else {
                        memcpy(var18, _leaf_down, 2 * sizeof(double));
                    }
                } else {
                    memcpy(var18, _leaf_down, 2 * sizeof(double));
                }
            } else {
                if (input[2] <= -1.2699999809265137) {
                    memcpy(var18, _leaf_down, 2 * sizeof(double));
                } else {
                    memcpy(var18, _leaf_up, 2 * sizeof(double));
                }
            }
        } else {
            if (input[3] <= 0.0406494140625) {
                if (input[1] <= 8.179999828338623) {
                    if (input[1] <= 2.9299999428912997) {
                        memcpy(var18, _leaf_down, 2 * sizeof(double));
                    } else {
                        if (input[5] <= 714.9105529785156) {
                            if (input[5] <= 104.6127815246582) {
                                if (input[5] <= 101.31917190551758) {
                                    memcpy(var18, _leaf_down, 2 * sizeof(double));
                                } else {
                                    memcpy(var18, _leaf_up, 2 * sizeof(double));
                                }
                            } else {
                                if (input[4] <= 1916.0750122070312) {
                                    if (input[4] <= 1838.2249755859375) {
                                        memcpy(var18, _leaf_down, 2 * sizeof(double));
                                    } else {
                                        memcpy(var18, _leaf_up, 2 * sizeof(double));
                                    }
                                } else {
                                    memcpy(var18, _leaf_down, 2 * sizeof(double));
                                }
                            }
                        } else {
                            memcpy(var18, _leaf_up, 2 * sizeof(double));
                        }
                    }
                } else {
                    if (input[8] <= 10.571061134338379) {
                        memcpy(var18, _leaf_down, 2 * sizeof(double));
                    } else {
                        memcpy(var18, _leaf_up, 2 * sizeof(double));
                    }
                }
            } else {
                memcpy(var18, _leaf_up, 2 * sizeof(double));
            }
        }
    } else {
        if (input[7] <= 0.6134033203125) {
            if (input[4] <= 17459.9501953125) {
                if (input[5] <= -106.32440185546875) {
                    memcpy(var18, _leaf_down, 2 * sizeof(double));
                } else {
                    memcpy(var18, _leaf_up, 2 * sizeof(double));
                }
            } else {
                if (input[6] <= 0.23010902106761932) {
                    if (input[1] <= 23.369999408721924) {
                        if (input[4] <= 20608.4248046875) {
                            memcpy(var18, _leaf_down, 2 * sizeof(double));
                        } else {
                            memcpy(var18, _leaf_up, 2 * sizeof(double));
                        }
                    } else {
                        if (input[5] <= -89.46052551269531) {
                            memcpy(var18, _leaf_down, 2 * sizeof(double));
                        } else {
                            memcpy(var18, _leaf_up, 2 * sizeof(double));
                        }
                    }
                } else {
                    memcpy(var18, _leaf_up, 2 * sizeof(double));
                }
            }
        } else {
            memcpy(var18, _leaf_up, 2 * sizeof(double));
        }
    }
    add_vectors(var3, var18, 2, var2);
    double var19[2];
    if (input[6] <= 0.07272932305932045) {
        if (input[5] <= 93.52481079101562) {
            if (input[7] <= -0.20550537109375) {
                if (input[7] <= -0.2069091796875) {
                    if (input[4] <= 1296.7999877929688) {
                        memcpy(var19, _leaf_up, 2 * sizeof(double));
                    } else {
                        if (input[0] <= 9444.0) {
                            memcpy(var19, _leaf_down, 2 * sizeof(double));
                        } else {
                            memcpy(var19, _leaf_up, 2 * sizeof(double));
                        }
                    }
                } else {
                    if (input[1] <= 8.28000020980835) {
                        if (input[8] <= 3.3224203884601593) {
                            memcpy(var19, _leaf_down, 2 * sizeof(double));
                        } else {
                            memcpy(var19, _leaf_up, 2 * sizeof(double));
                        }
                    } else {
                        memcpy(var19, _leaf_down, 2 * sizeof(double));
                    }
                }
            } else {
                memcpy(var19, _leaf_down, 2 * sizeof(double));
            }
        } else {
            if (input[8] <= 7.3343071937561035) {
                if (input[8] <= 2.287677526473999) {
                    memcpy(var19, _leaf_down, 2 * sizeof(double));
                } else {
                    if (input[4] <= 4105.75) {
                        if (input[4] <= 2132.0) {
                            if (input[5] <= 227.6169090270996) {
                                memcpy(var19, _leaf_up, 2 * sizeof(double));
                            } else {
                                memcpy(var19, _leaf_down, 2 * sizeof(double));
                            }
                        } else {
                            if (input[7] <= -0.20745849609375) {
                                if (input[5] <= 116.12894821166992) {
                                    memcpy(var19, _leaf_down, 2 * sizeof(double));
                                } else {
                                    memcpy(var19, _leaf_up, 2 * sizeof(double));
                                }
                            } else {
                                memcpy(var19, _leaf_down, 2 * sizeof(double));
                            }
                        }
                    } else {
                        if (input[1] <= 3.2050000429153442) {
                            memcpy(var19, _leaf_down, 2 * sizeof(double));
                        } else {
                            memcpy(var19, _leaf_up, 2 * sizeof(double));
                        }
                    }
                }
            } else {
                if (input[5] <= 626.1906127929688) {
                    if (input[7] <= -0.19586181640625) {
                        if (input[6] <= -0.8680902123451233) {
                            memcpy(var19, _leaf_up, 2 * sizeof(double));
                        } else {
                            memcpy(var19, _leaf_down, 2 * sizeof(double));
                        }
                    } else {
                        if (input[1] <= 6.390000104904175) {
                            if (input[6] <= -0.15720300376415253) {
                                memcpy(var19, _leaf_up, 2 * sizeof(double));
                            } else {
                                memcpy(var19, _leaf_down, 2 * sizeof(double));
                            }
                        } else {
                            if (input[3] <= 0.04107666015625) {
                                memcpy(var19, _leaf_down, 2 * sizeof(double));
                            } else {
                                memcpy(var19, _leaf_up, 2 * sizeof(double));
                            }
                        }
                    }
                } else {
                    memcpy(var19, _leaf_up, 2 * sizeof(double));
                }
            }
        }
    } else {
        if (input[3] <= -0.17535400390625) {
            if (input[0] <= 19379.0) {
                memcpy(var19, _leaf_down, 2 * sizeof(double));
            } else {
                if (input[6] <= 0.13086090236902237) {
                    if (input[4] <= 22611.275390625) {
                        memcpy(var19, _leaf_up, 2 * sizeof(double));
                    } else {
                        memcpy(var19, _leaf_down, 2 * sizeof(double));
                    }
                } else {
                    memcpy(var19, _leaf_up, 2 * sizeof(double));
                }
            }
        } else {
            if (input[5] <= 97.42481184005737) {
                memcpy(var19, _leaf_down, 2 * sizeof(double));
            } else {
                memcpy(var19, _leaf_up, 2 * sizeof(double));
            }
        }
    }
    add_vectors(var2, var19, 2, var1);
    mul_vector_number(var1, 0.1, 2, var0);
    memcpy(output, var0, 2 * sizeof(double));
}
