/* Auto-generated by train.py — do not edit manually.
 *
 * Stub model: returns equal class probabilities → no trigger event.
 * Replace this file with the output of:
 *   python tools/ml/train.py --output Core/Src/app/model_rf.c <labeled_csv>
 *
 * Input:  double[9]  — ML feature vector (see features.h)
 * Output: double[2]  — [P(FORCE_DOWN), P(FORCE_UP)]
 */
void score(double *input, double *output) {
    (void)input;
    output[0] = 0.5;
    output[1] = 0.5;
}
